server:
  port: 8080
  
spring:
  application:
    name: project2
  datasource:
    username: ${AWS_ROLE}
    password: ${AWS_PASS}
    url: jdbc:postgresql://revature2.chvwilb5xwei.us-east-1.rds.amazonaws.com:5432/postgres
  jpa:
    hibernate:      ddl-auto: update
  